version: "3.9"

networks:
  prod:
    driver: bridge

services:
  moor-app:
    image: docker.io/library/moor_app
    container_name: moor_app-services
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: Moor.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - app_files:/app/files
    networks:
      - prod
volumes:
  app_data:
  app_files:
